Create mapeadoresYouthMappersUFRJ.json
osmlab/osm-community-index pull request #764
Opened 2024-11-29 19:03 UTC by raqueldeziderio

Creates YouthMappers UFRJ mappers group.

2024-12-09 05:58 UTC, matkoniecz commented
1) please send github notification on github, not on my email

2) Only those with write access to this repository can merge pull requests. I am not such person

3) few days of waiting for PR merge is sort of normal on open source projects - getting some reply quicker is nice but not really to be expected

4) due to (3) - bothering people about unmerged PR is not so helpful

2024-12-09 06:02 UTC, matkoniecz requested changes

2024-12-09 06:02 UTC, matkoniecz commented on resources/south-america/brazil/mapeadoresYouthMappersUFRJ.json
> +    "include": ["076"];
this ; looks suspect, marked on github interface, seems confirmed by https://duckduckgo.com/?t=ffab&q=json+validator&ia=answer
```
Error: Parse error on line 6:
...  "include": ["076"];    "include": ["0
-----------------------^
Expecting 'EOF', '}', ',', ']', got 'undefined'
```

2024-12-09 06:05 UTC, matkoniecz commented on resources/south-america/brazil/mapeadoresYouthMappersUFRJ.json
> +    "url": "https://tasks.teachosm.org/users/YouthMappers"
this gives login wall if you have no third-party account

also, it seems to be YouthMappers link, not YouthMappers UFRJ link judging by URL

2024-12-09 07:18 UTC, raqueldeziderio commented
> 1. please send github notification on github, not on my email
> 2. Only those with write access to this repository can merge pull requests. I am not such person
> 3. few days of waiting for PR merge is sort of normal on open source projects - getting some reply quicker is nice but not really to be expected
> 4. due to (3) - bothering people about unmerged PR is not so helpful so even pinging me on github would not be wanted or OK
> 
> Please do not do this in future.
> 
> (if you ( @raqueldeziderio ) are unsure what is going on - then someone was pretending to be @raqueldeziderio and sending me emails about this PR)

I was me. But OK, I understand.

2024-12-16 15:03 UTC, bhousel commented
Same as #763 - should split all the resources into separate files.

2025-01-01 18:48 UTC, raqueldeziderio commented
> Same as #763 - should split all the resources into separate files.

Thank you, bhousel, I uploaded new files with your recomendation. Happy New Year!

2025-01-01 18:51 UTC, closed without merging